name: Build and Deploy aped-backend

on:
  push: 
    branches:
      - route-structure

jobs:
  build-deploy:
    name: Build and Deploy aped-backend
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - run: npm ci
      - run: npm run build --if-present
      - name: Deploy to remote server
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/apedbackend/ci-backend-test
            git pull origin route-structure
            npm ci
            npm run build --if-present
            # Add any additional deployment commands here
